### ISSUE TITLE
Does not follow spec of case insensitivity

### ISSUE THREAD

**Issue by jpSimkins** [eliblock/git-hooks#13]
Hello, thanks for this, you saved me a lot of time writing this myself. 

The only issue I have is that this script seems to be case-sensitive which is actually causing an issue since we use uppercase for all types. Not a serious issue but still something I wanted to point out. It seems a lot of these scripts force you to use lowercase even though the spec states it should not be treated as such.

> 15. The units of information that make up Conventional Commits MUST NOT be treated as case sensitive by implementors, with the exception of BREAKING CHANGE which MUST be uppercase.

Thanks again!

Reference: https://www.conventionalcommits.org/en/v1.0.0/#specification

**Comment by eliblock** [comment]
Hi @jpSimkins - thank you for opening this issue, and for providing the clear link to documentation. As you can see from my commit messages, I personally use lowercase types, so I hadn't noticed this inconsistency!

I'll take a look at addressing this in the next few days.
